// =============================================================
// Digital Hive — Site JS
// Mobile nav, scroll-triggered fades, sticky-nav border,
// testimonials carousel. No frameworks. ~80 lines.
// =============================================================

(function () {
  // ---------- Mega menu (enhances the static nav baked into every page) ----------
  // The nav + footer markup is generated by scripts/build-nav.mjs and lives in
  // the page HTML, so it's crawlable without JS. Here we only wire up behavior.
  function enhanceNav() {
    const nav = document.querySelector('.nav');
    if (!nav) return;

    // Current page detection (works for clean URLs and .html)
    const path = (location.pathname.split('/').pop() || 'home').toLowerCase().replace(/\.html$/, '');
    const dir  = location.pathname.replace(/\\/g, '/').split('/').slice(0, -1).pop() || '';

    // Skip-to-main link (screen readers + keyboard users) — injected once
    if (!document.querySelector('.skip-link')) {
      const mainEl = document.querySelector('main');
      if (mainEl && !mainEl.id) mainEl.id = 'top';
      const skip = document.createElement('a');
      skip.className = 'skip-link';
      skip.href = '#top';
      skip.textContent = 'Skip to main content';
      nav.parentElement.insertBefore(skip, nav);
    }

    // Active-state highlight for the current section
    const inPlatform  = ['product', 'usecases', 'connectors', 'security', 'architecture'].includes(path);
    const inResources = ['resources', 'faq', 'customers', 'blog'].includes(path) || dir === 'blog';
    const inCompany   = ['about', 'contact', 'partners'].includes(path);
    const activeKey =
      (inPlatform || path === 'home' || path === '') ? 'platform' :
      inResources ? 'resources' :
      inCompany   ? 'company' :
      path === 'pricing' ? 'pricing' : null;
    if (activeKey === 'pricing') {
      const p = nav.querySelector('.nav__plain');
      if (p) { p.classList.add('is-current'); p.setAttribute('aria-current', 'page'); }
    } else if (activeKey) {
      const t = nav.querySelector('[data-mega="' + activeKey + '"] .nav__trigger');
      if (t) { t.classList.add('is-current'); t.setAttribute('aria-current', 'page'); }
    }

    const navLinks = nav.querySelector('.nav__links');
    if (!navLinks) return;

    // ---- Hover / focus open/close with a short close-delay (lets pointer cross gap) ----
    const items = Array.from(navLinks.querySelectorAll('[data-mega]'));
    let closeTimer;
    const closeAll = () => {
      items.forEach(li => {
        li.classList.remove('is-open');
        const t = li.querySelector('.nav__trigger');
        const p = li.querySelector('.mega__panel');
        if (t) t.setAttribute('aria-expanded', 'false');
        if (p) { p.setAttribute('aria-hidden', 'true'); p.setAttribute('inert', ''); }
      });
    };
    const openOne = (li) => {
      items.forEach(other => other.classList.toggle('is-open', other === li));
      const t = li.querySelector('.nav__trigger');
      const p = li.querySelector('.mega__panel');
      if (t) t.setAttribute('aria-expanded', 'true');
      if (p) { p.setAttribute('aria-hidden', 'false'); p.removeAttribute('inert'); }
    };

    items.forEach(li => {
      const trigger = li.querySelector('.nav__trigger');
      li.addEventListener('mouseenter', () => {
        clearTimeout(closeTimer);
        openOne(li);
      });
      li.addEventListener('mouseleave', () => {
        clearTimeout(closeTimer);
        closeTimer = setTimeout(closeAll, 160);
      });
      // Click trigger → two-tap pattern:
      // • Desktop hover already opens the panel, so click goes straight to the page.
      // • Touch / keyboard: first tap opens the panel (preventDefault); second tap navigates.
      trigger.addEventListener('click', (e) => {
        if (!li.classList.contains('is-open')) {
          e.preventDefault();
          openOne(li);
        }
      });
      // Tab focus through links inside panel keeps it open
      li.addEventListener('focusin', () => { clearTimeout(closeTimer); openOne(li); });
      li.addEventListener('focusout', (e) => {
        if (!li.contains(e.relatedTarget)) {
          closeTimer = setTimeout(closeAll, 100);
        }
      });
    });

    // Esc closes
    document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeAll(); });
    // Click outside closes
    document.addEventListener('click', (e) => {
      if (!e.target.closest('.nav__links')) closeAll();
    });
  }
  enhanceNav();

  // ---------- Use-case PDF download tracking ----------
  // Delegated: catches every "Download the use case" link site-wide.
  // GA4 fires only once performance consent has loaded gtag.
  function setupDownloadTracking() {
    document.addEventListener('click', function (e) {
      const a = e.target.closest('a[download][href*="/assets/use-cases/"]');
      if (!a) return;
      if (!window.gtag) return;

      const fileName = (a.getAttribute('href').split('/').pop() || '').split('?')[0];

      window.gtag('event', 'file_download', {
        file_name:      fileName,
        file_extension: 'pdf',
        link_text:      (a.textContent || '').trim(),
      });
    });
  }
  setupDownloadTracking();

  // ---------- Client marquee — single source of truth for all logo strips ----------
  const CLIENT_NAMES = [
    'Bank <span class="sub">of</span> America',
    'Citigroup',
    'CIBC',
    'Ford',
    "Lowe's",
    'Takeda',
    'Trinity Health',
    'Westpac',
    'PATTISON',
    'Clarity',
    'DFS',
    'Highmark',
    'Froneri',
    'University <span class="sub">of</span> Denver',
  ];
  function setupClientMarquee() {
    document.querySelectorAll('[data-client-marquee]').forEach(function (row) {
      const items = CLIENT_NAMES.map(function (n) {
        return '<span class="proof__logo">' + n + '</span>';
      }).join('');
      row.innerHTML =
        '<div class="proof__track" aria-hidden="false">' + items + '</div>' +
        '<div class="proof__track" aria-hidden="true">'  + items + '</div>';
    });
  }
  setupClientMarquee();

  // ---------- Reading progress bar (long-form pages: blog articles + customer stories) ----------
  (function () {
    if (!document.querySelector('.art-body, .cs-doc')) return;
    var bar = document.createElement('div');
    bar.id = 'art-progress';
    bar.setAttribute('role', 'progressbar');
    bar.setAttribute('aria-label', 'Reading progress');
    bar.setAttribute('aria-valuemin', '0');
    bar.setAttribute('aria-valuemax', '100');
    document.body.appendChild(bar);
    function updateProgress() {
      var scrolled = window.scrollY;
      var total = document.documentElement.scrollHeight - window.innerHeight;
      var pct = total > 0 ? Math.min(scrolled / total, 1) : 0;
      // scaleX rather than width: composited, no layout on each scroll frame.
      bar.style.transform = 'scaleX(' + pct + ')';
      bar.setAttribute('aria-valuenow', Math.round(pct * 100));
    }
    window.addEventListener('scroll', updateProgress, { passive: true });
    updateProgress();
  })();

  // ---------- Sticky nav border on scroll ----------
  const nav = document.querySelector('.nav');
  const onScroll = () => {
    if (!nav) return;
    nav.classList.toggle('is-scrolled', window.scrollY > 4);
  };
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  // ---------- Mobile menu ----------
  const toggle = document.querySelector('[data-mobile-toggle]');
  const menu = document.querySelector('[data-mobile-menu]');
  if (toggle && menu) {
    toggle.addEventListener('click', () => {
      const open = menu.classList.toggle('is-open');
      toggle.setAttribute('aria-expanded', String(open));
    });
    menu.querySelectorAll('a').forEach((a) => {
      a.addEventListener('click', () => menu.classList.remove('is-open'));
    });
  }

  // ---------- Scroll reveal ----------
  const reveals = document.querySelectorAll('.reveal');
  if ('IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          io.unobserve(entry.target);
        }
      });
    }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });
    reveals.forEach((el) => io.observe(el));
  } else {
    reveals.forEach((el) => el.classList.add('is-visible'));
  }

  // ---------- Article TOC: mobile collapse + scroll-spy ----------
  const toc = document.querySelector('[data-toc]');
  if (toc) {
    // Mobile collapse — collapsed by default below 1000px
    const tocToggle = toc.querySelector('[data-toc-toggle]');
    if (tocToggle) {
      const mql = window.matchMedia('(min-width: 1000px)');
      const setCollapsed = (val) => toc.setAttribute('data-collapsed', String(val));
      setCollapsed(!mql.matches);
      mql.addEventListener('change', (e) => setCollapsed(!e.matches));
      tocToggle.addEventListener('click', () => {
        setCollapsed(toc.getAttribute('data-collapsed') !== 'true' ? true : false);
      });
    }

    // Scroll-spy
    if ('IntersectionObserver' in window) {
      const tocLinks = Array.from(toc.querySelectorAll('a[href^="#"]'));
      const sections = tocLinks
        .map((a) => document.getElementById(a.getAttribute('href').slice(1)))
        .filter(Boolean);

      const tocIO = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const id = entry.target.id;
            tocLinks.forEach((a) =>
              a.classList.toggle('is-current', a.getAttribute('href') === '#' + id)
            );
          }
        });
      }, { rootMargin: '-30% 0px -55% 0px', threshold: 0 });
      sections.forEach((s) => tocIO.observe(s));
    }
  }

  // ---------- Resource library filter ----------
  const library = document.querySelector('[data-library]');
  if (library) {
    const tabs = Array.from(library.querySelectorAll('[data-filter]'));
    const cards = Array.from(library.querySelectorAll('.res-card'));

    // Initialize tab counts
    const counts = { all: cards.length };
    cards.forEach((c) => {
      const t = c.dataset.type;
      counts[t] = (counts[t] || 0) + 1;
    });
    tabs.forEach((tab) => {
      const c = tab.querySelector('.count');
      if (c) c.textContent = counts[tab.dataset.filter] || 0;
      // Hide tabs with no matching content (except "All")
      if (tab.dataset.filter !== 'all') {
        tab.hidden = !(counts[tab.dataset.filter] > 0);
      }
    });

    const apply = (filter) => {
      let shown = 0;
      cards.forEach((c) => {
        const match = filter === 'all' || c.dataset.type === filter;
        c.style.display = match ? '' : 'none';
        if (match) shown++;
      });
      library.classList.toggle('is-empty', shown === 0);
    };

    tabs.forEach((tab) => {
      tab.addEventListener('click', () => {
        tabs.forEach((t) => {
          const active = t === tab;
          t.classList.toggle('is-active', active);
          if (t.getAttribute('role') === 'tab') t.setAttribute('aria-selected', active ? 'true' : 'false');
        });
        apply(tab.dataset.filter);
      });
    });
  }

  // ---------- Use case card expand (mobile) ----------
  document.querySelectorAll('[data-uc-expand]').forEach((btn) => {
    btn.addEventListener('click', (e) => {
      // Card is wrapped in <a>; prevent navigation when toggling on mobile.
      e.preventDefault();
      e.stopPropagation();
      const card = btn.closest('.uc-card');
      if (!card) return;
      const open = card.classList.toggle('is-expanded');
      btn.setAttribute('aria-expanded', String(open));
      const label = btn.querySelector('span');
      if (label) label.textContent = open ? 'Hide outcomes' : '3 outcomes';
    });
  });

  // ---------- FAQ: categories, accordion, search ----------
  const faqNav = document.querySelector('[data-faq-nav]');
  if (faqNav) {
    const links = Array.from(faqNav.querySelectorAll('.faq-nav__link'));
    const panels = Array.from(document.querySelectorAll('.faq-panel'));
    const items = Array.from(document.querySelectorAll('.faq-item'));
    const search = document.querySelector('[data-faq-search]');
    const emptyState = document.querySelector('[data-faq-empty]');

    const showCategory = (cat) => {
      links.forEach(l => {
        const active = l.dataset.cat === cat;
        l.classList.toggle('is-current', active);
        l.setAttribute('aria-pressed', active ? 'true' : 'false');
      });
      panels.forEach(p => p.classList.toggle('is-current', p.dataset.panel === cat));
      if (emptyState) emptyState.classList.remove('is-on');
      if (search) search.value = '';
      // Collapse all open
      items.forEach(i => i.classList.remove('is-open'));
      // Scroll panel into view on mobile
      if (window.innerWidth < 1000) {
        const visible = document.querySelector('.faq-panel.is-current');
        if (visible) window.scrollTo({ top: visible.offsetTop - 80, behavior: 'smooth' });
      }
    };

    links.forEach(l => l.addEventListener('click', () => showCategory(l.dataset.cat)));

    // Accordion toggle (open one, close siblings within same panel)
    items.forEach(item => {
      const btn = item.querySelector('.faq-item__q');
      if (!btn) return;
      btn.addEventListener('click', () => {
        const willOpen = !item.classList.contains('is-open');
        const panel = item.closest('.faq-panel');
        if (panel) panel.querySelectorAll('.faq-item').forEach(i => i.classList.remove('is-open'));
        item.classList.toggle('is-open', willOpen);
        btn.setAttribute('aria-expanded', String(willOpen));
      });
    });

    // Search across ALL items
    if (search) {
      search.addEventListener('input', () => {
        const q = search.value.trim().toLowerCase();
        if (!q) {
          // Restore category view
          panels.forEach(p => p.classList.toggle('is-current', p.dataset.panel === (links.find(l => l.classList.contains('is-current')) || links[0]).dataset.cat));
          items.forEach(i => { i.style.display = ''; i.classList.remove('is-open'); });
          if (emptyState) emptyState.classList.remove('is-on');
          return;
        }
        // Show all panels, filter items
        panels.forEach(p => p.classList.add('is-current'));
        let shown = 0;
        items.forEach(i => {
          const text = i.textContent.toLowerCase();
          const match = text.includes(q);
          i.style.display = match ? '' : 'none';
          if (match) shown++;
        });
        // Hide panel heads when searching to avoid duplicated headers
        document.querySelectorAll('.faq-panel__head').forEach(h => h.style.display = 'none');
        if (emptyState) emptyState.classList.toggle('is-on', shown === 0);
      });
      search.addEventListener('blur', () => {
        if (!search.value.trim()) {
          document.querySelectorAll('.faq-panel__head').forEach(h => h.style.display = '');
        }
      });
      // ⌘K to focus
      document.addEventListener('keydown', (e) => {
        if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
          e.preventDefault();
          search.focus();
        }
      });
    }

    // Deep-link to category via hash (#pricing, #security, etc.)
    const initialHash = (location.hash || '').replace('#', '');
    if (initialHash && links.find(l => l.dataset.cat === initialHash)) {
      showCategory(initialHash);
    }
  }

  // ---------- Connectors filter ----------
  const cnGrid = document.querySelector('[data-connectors]');
  if (cnGrid) {
    const filters = Array.from(document.querySelectorAll('[data-cn-filter]'));
    const cards = Array.from(cnGrid.querySelectorAll('.cn-card'));
    const counts = { all: cards.length };
    cards.forEach(c => {
      (c.dataset.cat || '').split(/\s+/).filter(Boolean).forEach(cat => {
        counts[cat] = (counts[cat] || 0) + 1;
      });
    });
    filters.forEach(f => {
      const cEl = f.querySelector('.count');
      if (cEl) cEl.textContent = counts[f.dataset.cnFilter] || 0;
    });
    const apply = (filter) => {
      cards.forEach(c => {
        const cats = (c.dataset.cat || '').split(/\s+/);
        c.style.display = (filter === 'all' || cats.includes(filter)) ? '' : 'none';
      });
    };
    filters.forEach(f => f.addEventListener('click', () => {
      filters.forEach(o => {
        const active = o === f;
        o.classList.toggle('is-on', active);
        o.setAttribute('aria-pressed', active ? 'true' : 'false');
      });
      apply(f.dataset.cnFilter);
    }));
  }

  // ---------- Count-up animation ----------
  const countEls = document.querySelectorAll('[data-count-up]');
  if (countEls.length && 'IntersectionObserver' in window) {
    const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const runCount = (el) => {
      const target   = parseFloat(el.dataset.countUp);
      const decimals = parseInt(el.dataset.countDecimals || '0', 10);
      const duration = 1200;
      const startTime = performance.now();
      const easeOut  = (t) => 1 - Math.pow(1 - t, 3);
      const tick = (now) => {
        const progress = Math.min((now - startTime) / duration, 1);
        el.textContent = (easeOut(progress) * target).toFixed(decimals);
        if (progress < 1) requestAnimationFrame(tick);
        else el.textContent = target.toFixed(decimals);
      };
      el.textContent = (0).toFixed(decimals);
      requestAnimationFrame(tick);
    };

    const countIO = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        countIO.unobserve(entry.target);
        if (!reducedMotion) runCount(entry.target);
      });
    }, { threshold: 0.6 });
    countEls.forEach((el) => countIO.observe(el));
  }

  // ---------- Governance bar chart ----------
  const govBars = document.querySelector('.mock-gov__bars');
  if (govBars && 'IntersectionObserver' in window) {
    const barIO = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.querySelectorAll('.bar').forEach((bar, i) => {
            const pct = parseFloat(bar.dataset.barH) || 0;
            bar.style.height = pct + '%';
            setTimeout(() => { bar.classList.add('is-grown'); }, i * 45);
          });
          barIO.unobserve(entry.target);
        }
      });
    }, { threshold: 0.4 });
    barIO.observe(govBars);
  }

  // ---------- Testimonials carousel ----------
  const carousel = document.querySelector('[data-carousel]');
  if (carousel) {
    const slides = Array.from(carousel.querySelectorAll('.carousel__slide'));
    const dots = Array.from(carousel.querySelectorAll('.carousel__dot'));
    const prev = carousel.querySelector('[data-carousel-prev]');
    const next = carousel.querySelector('[data-carousel-next]');
    let idx = 0;
    let timer;

    const go = (n) => {
      idx = (n + slides.length) % slides.length;
      slides.forEach((s, i) => s.classList.toggle('is-active', i === idx));
      dots.forEach((d, i) => {
        d.classList.toggle('is-active', i === idx);
        d.setAttribute('aria-pressed', i === idx ? 'true' : 'false');
      });
    };
    const start = () => {
      stop();
      timer = setInterval(() => go(idx + 1), 7000);
    };
    const stop = () => { if (timer) clearInterval(timer); };

    dots.forEach((d, i) => d.addEventListener('click', () => { go(i); start(); }));
    prev && prev.addEventListener('click', () => { go(idx - 1); start(); });
    next && next.addEventListener('click', () => { go(idx + 1); start(); });

    carousel.addEventListener('mouseenter', stop);
    carousel.addEventListener('mouseleave', start);

    go(0);
    start();
  }
})();
